Develop
CYX4Rb/Snake-JS pull request #8
Opened 2021-01-26 22:18 UTC by CYX4Rb

completed 
https://github.com/CYX4Rb/Snake-JS/issues/3
https://github.com/CYX4Rb/Snake-JS/issues/6

2021-01-27 15:36 UTC, bogdanovsi requested changes

2021-01-27 15:36 UTC, bogdanovsi commented on js/index.js
> +            if (snake[0].x < 0 || snake[0].x > 450 || snake[0].y < 0 || snake[0].y > 450 || crash(snake)) {
Необходимо вынести в отдельную функцию `isGameOver`

2021-01-27 15:36 UTC, bogdanovsi commented on js/index.js
> +pause.addEventListener('click', () => isPaused ?  isPaused = false : isPaused =  true)
Можно упросить до `isPaused = !isPaused`

2021-01-27 15:36 UTC, bogdanovsi commented on js/index.js
> +})
Поправить форматирование файла, совсем нету отступов.

2021-01-29 16:11 UTC, CYX4Rb commented on js/index.js
> +})
fix

2021-01-29 16:11 UTC, CYX4Rb commented on js/index.js
> +pause.addEventListener('click', () => isPaused ?  isPaused = false : isPaused =  true)
fix

2021-01-29 16:11 UTC, CYX4Rb commented on js/index.js
> +            if (snake[0].x < 0 || snake[0].x > 450 || snake[0].y < 0 || snake[0].y > 450 || crash(snake)) {
fix

2021-01-29 16:12 UTC, bogdanovsi approved these changes

2021-01-29 16:12 UTC, merged